theme: jekyll-theme-modernist
title: Welcome to the 154959's homepage!
desciption: Feel free to bookmark this to keep an eye on my project updates


Heading 1: " The Joker "
Text: In 2019 in October month started a movie with name " Joker ". It was a story about the ill person, whose many sick was in his brain.
His illness was an awful laugh, which he could not control and that's why in the community he can not be exsited, beacause he is not a regular.
The whole world was telling, that everyone with kind of illness must act like a normal, so the community could live proparly and not be interapted
by of them. 
